sudo: false

language: node_js
node_js:
  - 14

cache:
  directories:
    - $HOME/node_modules
    - $HOME/client/node_modules

install:
  - npm install
  - cd client && npm install && cd ../

script:
  - npm test
  - npm run devTest